name: imperio_mock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.7
  google_fonts: 6.0.0
  http: ^1.1.2
  intl: ^0.19.0
  iconly: ^1.0.1
  shared_preferences: ^2.2.3
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
  bloc_test: ^9.1.5
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/