import 'package:get_it/get_it.dart';
import 'package:http/http.dart' as http;
import 'package:imperio_mock/app/modules/auth/data/datasources/auth_datasource.dart';
import 'package:imperio_mock/app/modules/auth/data/repo/auth_repo.dart';
import 'package:imperio_mock/app/modules/auth/domain/usecases/cache_user.dart';
import 'package:imperio_mock/app/modules/auth/domain/usecases/check_user_logged.dart';
import 'package:imperio_mock/app/modules/auth/domain/usecases/sign_in.dart';
import 'package:imperio_mock/app/modules/auth/presenter/bloc/auth_bloc.dart';
import 'package:imperio_mock/app/modules/home/data/datasource/home_data_source.dart';
import 'package:imperio_mock/app/modules/home/data/repo/home_repo.dart';
import 'package:imperio_mock/app/modules/home/domain/usecases/get_matches.dart';
import 'package:imperio_mock/app/modules/home/domain/usecases/list_of_bonus.dart';
import 'package:imperio_mock/app/modules/home/domain/usecases/list_of_championships.dart';
import 'package:imperio_mock/app/modules/home/domain/usecases/list_of_tips.dart';
import 'package:imperio_mock/app/modules/home/domain/usecases/list_of_won_bets.dart';
import 'package:imperio_mock/app/modules/home/presenter/bloc/home_bloc.dart';
import 'package:imperio_mock/app/modules/sports/data/datasource/sports_datasource.dart';
import 'package:imperio_mock/app/modules/sports/data/repo/sports_repo.dart';
import 'package:imperio_mock/app/modules/sports/domain/usecases/get_sports.dart';
import 'package:imperio_mock/app/modules/sports/presentation/bloc/sports_bloc.dart';
import 'package:shared_preferences/shared_preferences.dart';

part 'injection_container.main.dart';
